[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/"
  to = "/vi/"
  status = 302

[[redirects]]
  from = "/ko/*"
  to = "/ko/:splat"
  status = 200

[[redirects]]
  from = "/vi/*" 
  to = "/vi/:splat"
  status = 200

[[redirects]]
  from = "/en/*"
  to = "/en/:splat"
  status = 200

[[redirects]]
  from = "/zh/*"
  to = "/zh/:splat"  
  status = 200

[[redirects]]
  from = "/ja/*"
  to = "/ja/:splat"
  status = 200

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true